#!/usr/bin/env bash

# ───────────────────────────────────────────────────────────────
#                      Theme Settings
# ───────────────────────────────────────────────────────────────
dir="$HOME/.config/rofi/settings/theme_switcher/"

# ───────────────────────────────────────────────────────────────
#                         Menu Options
# ───────────────────────────────────────────────────────────────
theme1='LAPTOP'
theme2='HMDI'
theme3='DUAL'
theme4='TRIPLE'

# ───────────────────────────────────────────────────────────────
#                           User Info
# ───────────────────────────────────────────────────────────────
username=" $(whoami)"
messages=("Which display setup do you want?" "Select a setup to apply!" "Choose your preferred Display Setup!")

# Pick a random message
sendoff="${messages[$((RANDOM % ${#messages[@]}))]}"

# ───────────────────────────────────────────────────────────────
#                           Rofi Cmd
# ───────────────────────────────────────────────────────────────
rofi_cmd() {
    rofi -dmenu \
        -p "$username" \
        -mesg "$sendoff" \
        -theme ${dir}/cozy.rasi
}

# ───────────────────────────────────────────────────────────────
#                       Run Rofi Menu
# ───────────────────────────────────────────────────────────────
run_rofi() {
    echo -e "$theme1\n$theme2\n$theme3\n$theme4" | rofi_cmd
}

# ───────────────────────────────────────────────────────────────
#                        Command Exec
# ───────────────────────────────────────────────────────────────
run_cmd() {
    case $1 in
        "$theme1")
            ~/.config/rofi/scripts/monitorswitching.sh "DP"
            ;;
        "$theme2")
            ~/.config/rofi/scripts/monitorswitching.sh "HDMI"
            ;;
        "$theme3")
            ~/.config/rofi/scripts/monitorswitching.sh "DUAL"
            ;;
        "$theme4")
            ~/.config/rofi/scripts/monitorswitching.sh "TRIPLE"
            ;;
    esac
}

# ───────────────────────────────────────────────────────────────
#                           Execute Cmd
# ───────────────────────────────────────────────────────────────
chosen="$(run_rofi)"
run_cmd "$chosen"
