format = """\
$username\
[](fg:#bd93f9)\
$hostname\
$directory\
[ ](fg:#bd93f9)\
$git_branch\
$git_status\
$all\
$character"""
# Disable the blank line at the start of the prompt
add_newline = true

[line_break]
disabled = true

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "fg:#ff79c6 "
style_root = "fg:#ff79c6 "
format = '[   󰦈 ]($style)' # $user

[hostname]
ssh_only = true
ssh_symbol = '󰖟 '
style = "fg:#8be9fd "
format = ' [$ssh_symbol$hostname]($style)'

[directory]
style = "fg:#8be9fd "
format = " [ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"~" = " "
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰽰"
"Pictures" = " "
"videos" = " "
"important" = "󰜦 "
"uni" = "󰑴 "
# Keep in mind that the order matters. For example:
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = " "
style = "fg:#50fa7b "
format = '[ $symbol $branch(:$remote_branch) ]($style)'

[git_status]
style = "fg:#50fa7b "
ahead = "󰶣 ${count} "
diverged = "󰶣 ${ahead_count} 󰶡 ${behind_count} "
behind = "󰶡 ${count} "
deleted = "󰆴 "
modified = "󰷈 "
up_to_date = " "
format = '[$all_status$ahead_behind ]($style)'


[aws]
symbol = " "
style = "fg:#f1fa8c "
format = '[ $symbol ($version )]($style)'

[conda]
symbol = ""
style = "fg:#f1fa8c "
format = '[ $symbol ($version )]($style)'

[dart]
symbol = ""
style = "fg:#f1fa8c "
format = '[ $symbol ($version )]($style)'

[c]
symbol = ""
style = "fg:#f1fa8c "
format = '[ $symbol ($version )]($style)'
detect_extensions = ["c", "cpp", "h"] 

[docker_context]
symbol = ""
style = "fg:#f1fa8c "
format = '[ $symbol $context]($style) $path '

[elixir]
symbol = ""
style = "fg:#f1fa8c "
format = '[ $symbol ($version )]($style)'

[elm]
symbol = ""
style = "fg:#f1fa8c "
format = '[ $symbol ($version )]($style)'

[golang]
symbol = "ﳑ"
style = "fg:#f1fa8c "
format = '[ $symbol ($version )]($style)'

[haskell]
symbol = "λ"
style = "fg:#f1fa8c "
format = '[ $symbol ($version )]($style)'

[java]
symbol = ""
style = "fg:#f1fa8c "
format = '[ $symbol ($version )]($style)'

[julia]
symbol = ""
style = "fg:#f1fa8c "
format = '[ $symbol ($version )]($style)'

[lua]
symbol = ""
style = "fg:#f1fa8c "
format = '[ $symbol ($version )]($style)'

[nim]
symbol = ""
style = "fg:#f1fa8c "
format = '[ $symbol ($version )]($style)'

[nix_shell]
symbol = ""
style = "fg:#f1fa8c "
format = '[ $symbol ($version )]($style)'

[nodejs]
symbol = ""
style = "fg:#f1fa8c "
format = '[ $symbol ($version )]($style)'

[perl]
symbol = ""
style = "fg:#f1fa8c "
format = '[ $symbol ($version )]($style)'

[php]
symbol = ""
style = "fg:#f1fa8c "
format = '[ $symbol ($version )]($style)'

[python]
symbol = ""
style = "fg:#f1fa8c "
format = '[ $symbol ($version )]($style)'

[ruby]
symbol = ""
style = "fg:#f1fa8c "
format = '[ $symbol ($version )]($style)'

[rust]
symbol = ""
style = "fg:#f1fa8c "
format = '[ $symbol ($version )]($style)'

[swift]
symbol = "ﯣ"
style = "fg:#f1fa8c "
format = '[ $symbol ($version )]($style)'

[package]
symbol = ""
style = "fg:#f1fa8c "
format = "[ $symbol $version]($style)"
disabled = true


[cmd_duration]
min_time = 1
style = "fg:#f9e2af "
format = "[ $duration]($style)"
disabled = true

[jobs]
symbol = "華"
style = "fg:#f9e2af "
format = "[ $symbol]($style)"

[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "
unknown_symbol = " "
empty_symbol = " "
format = "[ $symbol$percentage ]($style )"
disabled = true

[[battery.display]]
threshold = 15
style = "bold fg:#CAA9E0"

[[battery.display]]
threshold = 50
style = "fg:#f9e2af"

[[battery.display]]
threshold = 101
style = "bold #a6e3a1"

# Prompt: optional param 1
[time]
disabled = true
time_format = "%R"
style = ""
format = '[](fg:#333a56 $style)[  $time ](fg:#94e2d5 $style)'

# Last param in the first line/row
# fg:#3b4363 if time enabled
[character]
success_symbol = "[](fg:#f1fa8c)"
error_symbol = "[](fg:#ff5555)"
